# Generated by Django 2.1 on 2019-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_upvoted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_approved',
            field=models.BooleanField(default=False),
        ),
    ]
