# Generated by Django 2.1 on 2019-08-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_post_considered'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_approvals',
            field=models.IntegerField(default=0),
        ),
    ]
